### ISSUE TITLE
Bootloop Issue

### ISSUE THREAD

**Issue by thefaizanbashir** [UtsavBalar1231/kernel_xiaomi_raphael#15]
Hey Utsav! Thanks for your work! I'm not criticising you! I'm just reporting a serious issue, so that you can make it better! I'm on Evolution X, whenever i flash your kernel i always stuck into bootloop. Can you please fix this issue? I tried all troubleshooting steps. Still facing the same issue!

**Comment by kondors1995** [comment]
issue is due to evo ussing q vendor and eimensity i utilizing R changes for encription with Q vendor wont support

**Comment by UtsavBalar1231** [comment]
> Hey Utsav! Thanks for your work! I'm not criticising you! I'm just reporting a serious issue, so that you can make it better! I'm on Evolution X, whenever i flash your kernel i always stuck into bootloop. Can you please fix this issue? I tried all troubleshooting steps. Still facing the same issue!

It wont work unless your ROM adds support for android 11 encryption update, moreover it is recommended to use android10 kernels for ROMa that are still utilising android 10 prebuilt vendor

**Comment by thefaizanbashir** [comment]
Thanks Utsav, for speedy update! Thanks

**Comment by thefaizanbashir** [comment]
Thanks Utsav Sir!
