### ISSUE TITLE
 Hello please help me about compiling the kernel

### ISSUE THREAD

**Issue by maozhifeng** [UtsavBalar1231/kernel_xiaomi_raphael#5]
Dear developer senior, Hello, I recently had a problem when compiling your kernel. I failed to compile your kernel source code configuration raphael-stock_defconfig and raphael_defconfig using Qualcomm clang and google clang and google dtc, But I was able to successfully compile Image.gz-dtb through Xiaomi ’s official kernel. Can you publish your clang version, dtc version and the corresponding environment configuration?
Thank you very much.

**Comment by maozhifeng** [comment]
Thank you, I have compiled successfully, but the built-in camera is not functioning properly, and it cannot drag normally when I use the front camera. I use the configuration raphael_defconfig.

**Comment by maozhifeng** [comment]
Thank you very much for your great creation. Now it's very good.



I mainly want to modify the wireless network card of the kernel for the wireless penetration test of Kali nethunter. At present, I can normally add rt8187, rt3072 and hid drivers, but when I add the ath9271 wireless network card driver module, there will be errors. I don't know how to solve it. Through search, it seems to be caused by repeated use of the value of ath6. Can you help me add this driver, thank you, thank you, thank you, thank you!!!!!
![20200308205254](https://user-images.githubusercontent.com/37328485/76163210-2eac3500-617f-11ea-8682-d5c48cc865e6.png)

**Comment by maozhifeng** [comment]
You can see that this is my ath9k driver configuration. When I add the two options of "Atheros HTC based wireless cards support" and "Atheros 802.11n Wireless cards support", the above error will appear when compiling.

![12320200308211121](https://user-images.githubusercontent.com/37328485/76163480-65834a80-6181-11ea-9e1f-28cd6679565d.png)

**Comment by maozhifeng** [comment]
Before adding these drivers, I made a kernel patc
[redmi-k20pro-master2-mac80211-hid.txt](https://github.com/UtsavBalar1231/kernel_xiaomi_raphael/files/4303232/redmi-k20pro-master2-mac80211-hid.txt)

h, which is my kernel patch:

**Comment by maozhifeng** [comment]
Before adding these drivers, I made a kernel patch, which is my kernel patch:
[redmi-k20pro-master2-mac80211-hid.txt](https://github.com/UtsavBalar1231/kernel_xiaomi_raphael/files/4303233/redmi-k20pro-master2-mac80211-hid.txt)

**Comment by UtsavBalar1231** [comment]
> Thank you very much for your great creation. Now it's very good.
> 
> I mainly want to modify the wireless network card of the kernel for the wireless penetration test of Kali nethunter. At present, I can normally add rt8187, rt3072 and hid drivers, but when I add the ath9271 wireless network card driver module, there will be errors. I don't know how to solve it. Through search, it seems to be caused by repeated use of the value of ath6. Can you help me add this driver, thank you, thank you, thank you, thank you!!!!!
> ![20200308205254](https://user-images.githubusercontent.com/37328485/76163210-2eac3500-617f-11ea-8682-d5c48cc865e6.png)

You can remove declaration of those multiple variables from the new ath driver

**Comment by maozhifeng** [comment]
Sorry, I don't know C language, I don't know how to modify it. Can you give me a kernel patch or a specific hint?? Thank you

**Comment by UtsavBalar1231** [comment]
> Sorry, I don't know C language, I don't know how to modify it. Can you give me a kernel patch or a specific hint?? Thank you

i Can't help you if you dont have basics of C

**Comment by maozhifeng** [comment]
Please help me. I really want to learn how to modify it. I know a little bit of C language, but I can't reach the ability to modify it. The only computer language I'm proficient in now is python。

Please give me a hint, maybe I can change it

Can I comment out the code?
![QQ图片20200309161333](https://user-images.githubusercontent.com/37328485/76194394-070da900-6221-11ea-95cf-bda3a51d77eb.png)
![QQ图片20200309162125](https://user-images.githubusercontent.com/37328485/76194931-3670e580-6222-11ea-9983-23d54bc4d284.png)
![QQ图片20200309162149](https://user-images.githubusercontent.com/37328485/76194949-3e308a00-6222-11ea-855b-50b7273025a3.png)

**Comment by UtsavBalar1231** [comment]
send me the driver i ll fix it for you

**Comment by maozhifeng** [comment]
The driver name is AR9271:
![76163480-65834a80-6181-11ea-9e1f-28cd6679565d](https://user-images.githubusercontent.com/37328485/76196394-1ee72c00-6225-11ea-95c3-41f312e22fd9.png)
the two options of "Atheros HTC based wireless cards support" and "Atheros 802.11n Wireless cards support"

I commented the code just now and compiled successfully, but I don't know if I can achieve its function.


![QQ图片20200309164122](https://user-images.githubusercontent.com/37328485/76196283-f101e780-6224-11ea-98f7-f4b6003e77f4.png)

**Comment by maozhifeng** [comment]
These three documents：
[htc.txt](https://github.com/UtsavBalar1231/kernel_xiaomi_raphael/files/4305570/htc.txt)
[htc_hst.txt](https://github.com/UtsavBalar1231/kernel_xiaomi_raphael/files/4305572/htc_hst.txt)
[htc_services.txt](https://github.com/UtsavBalar1231/kernel_xiaomi_raphael/files/4305573/htc_services.txt)

**Comment by maozhifeng** [comment]
. TXT suffix changed to. C

**Comment by maozhifeng** [comment]
https://wireless.wiki.kernel.org/en/users/drivers/ath9k_htc

**Comment by maozhifeng** [comment]
Tested, driver for ar9271 is not available after code comment.
