### ISSUE TITLE
Terminal emulators don't work with this kernel

### ISSUE THREAD

**Issue by justifiableObesity** [UtsavBalar1231/kernel_xiaomi_raphael#8]
Title explains all, if you switch to the regular xiaomi kernel, then emulators like Termux and UserLAnd will work.

Try it out for yourself by installing Termux and running it. At first it might seem normal and all, but once you restart all symbolic links are lost and you cannot use the app.

**Comment by UtsavBalar1231** [comment]
Is this bug you are facing on MIUI ?

**Comment by justifiableObesity** [comment]
> Is this bug you are facing on MIUI ?

No, I am running LOS 17.1

**Comment by maozhifeng** [comment]
I use the Linux_deploy app used by miui11, which can be used normally. But when I switch on and off the machine again, I need to remove and update the environment in the setting of Linux_deploy app, so that it can be used normally again. I don't know if this has something to do with the kernel.
